//
//  CitiesWorker.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CitiesWorker
{
    func fetchCities() -> [Cities.City] {
        return [
            Cities.City(name: "Sumy", population: 230_000),
            Cities.City(name: "Kyiv", population: 2_300_000),
            Cities.City(name: "Kharkiv", population: 1_200_00),
            Cities.City(name: "Lviv", population: 890_000),
            Cities.City(name: "Odesa", population: 1_342_000),
            ]
    }
}
