//
//  CitiesModels.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Cities
{
    // MARK: Use cases
    
    struct City {
        let name: String
        let population: Int
    }
    
    struct CityViewModel {
        let title: String
    }
    
    enum FetchCities
    {
        struct Request {
            
        }
        
        struct Response {
            let cities: [City]
        }
        
        struct ViewModel {
            let rows: [CityViewModel]
        }
        
    }
}
