//
//  CitiesPresenter.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesPresentationLogic
{
  func presentCities(response: Cities.FetchCities.Response)
}

class CitiesPresenter: CitiesPresentationLogic
{
  weak var viewController: CitiesDisplayLogic?
  
  // MARK: Do something
  
  func presentCities(response: Cities.FetchCities.Response)
  {
      
      let rows = response.cities.map { city in
          let formattePopulation = formatPopulation(city.population)
          let title = "\(city.name) - \(formattePopulation) population"
          return Cities.CityViewModel(title: title)
      }
      
    let viewModel = Cities.FetchCities.ViewModel(rows: rows)
    viewController?.displayCities(viewModel: viewModel)
  }
    
    private func formatPopulation(_ population: Int) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.groupingSeparator = " "
        return formatter.string(from: NSNumber(value: population)) ?? "\(population)"
    }

}
