//
//  PeopleListModels.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PeopleList
{
    // MARK: Use cases
    
    struct Person {
        var name: String
        var age: Int
    }
    
    struct PersonViewModel {
        var title: String
    }
    
    enum FetchPeople
    {
        struct Request
        {
        }
        struct Response
        {
            var people: [Person]
        }
        struct ViewModel
        {
            var rows: [PersonViewModel]
        }
    }
}
