//
//  PeopleListViewController.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PeopleListDisplayLogic: class
{
    func displayPeople(viewModel: PeopleList.FetchPeople.ViewModel)
}

class PeopleListViewController: UIViewController, PeopleListDisplayLogic
{
    var interactor: PeopleListBusinessLogic?
    var router: (NSObjectProtocol & PeopleListRoutingLogic & PeopleListDataPassing)?
    
    private var tableView = UITableView()
    private var rows: [PeopleList.PersonViewModel] = []
    
    //MARK: - Setup Table View
    
    private func setupTableView() {
        tableView.frame = view.bounds
        tableView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        tableView.dataSource = self
        tableView.delegate = self
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
        view.addSubview(tableView)
    }
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = PeopleListInteractor()
        let presenter = PeopleListPresenter()
        let router = PeopleListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setupTableView()
        doSomething()
    }
    
    
    func doSomething()
    {
        let request = PeopleList.FetchPeople.Request()
        interactor?.fethcPeople(request: request)
    }
    
    func displayPeople(viewModel: PeopleList.FetchPeople.ViewModel)
    {
        rows = viewModel.rows
        tableView.reloadData()
    }
}

extension PeopleListViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return rows.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell", for: indexPath)
        cell.textLabel?.text = rows[indexPath.row].title
        return cell
    }
    
    
}

extension PeopleListViewController: UITableViewDelegate {
    
}
