//
//  PeopleListPresenter.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PeopleListPresentationLogic
{
    func presentPeople(response: PeopleList.FetchPeople.Response)
}

class PeopleListPresenter: PeopleListPresentationLogic
{
    weak var viewController: PeopleListDisplayLogic?
    
    // MARK: Do something
    
    func presentPeople(response: PeopleList.FetchPeople.Response)
    {
        
        let rows = response.people.map { person in
            let title = person.name + " is \(person.age) years old"
            return PeopleList.PersonViewModel(title: title)
        }
        
        let viewModel = PeopleList.FetchPeople.ViewModel(rows: rows)
        viewController?.displayPeople(viewModel: viewModel)
    }
}
