//
//  PeopleListRouter.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PeopleListRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routToDetailsScreen(at index: Int)
}

protocol PeopleListDataPassing
{
    var dataStore: PeopleListDataStore? { get }
}

class PeopleListRouter: NSObject, PeopleListRoutingLogic, PeopleListDataPassing
{

    
    weak var viewController: PeopleListViewController?
    var dataStore: PeopleListDataStore?
    
    func routToDetailsScreen(at index: Int) {
        guard let person = dataStore?.people[index] else { return }
        
        let detailsVC = PersonDetailsViewController()
        detailsVC.person = person
        viewController?.navigationController?.pushViewController(detailsVC, animated: true)
    }
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: PeopleListViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: PeopleListDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
