//
//  PeopleListWorker.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PeopleListWorker
{
    func fetchPeople() -> [PeopleList.Person] {
        return [
            PeopleList.Person(name: "Ruslan", age: 23),
            PeopleList.Person(name: "Yana", age: 20),
            PeopleList.Person(name: "Arsen", age: 24),
            PeopleList.Person(name: "Eugene", age: 25),
            PeopleList.Person(name: "Bogdan", age: 24),
            PeopleList.Person(name: "Petro", age: 13)
        ]
    }
}
