//
//  PeopleListInteractor.swift
//  Clean Swift Test
//
//  Created by Ruslan Liulka on 25.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PeopleListBusinessLogic
{
    func fethcPeople(request: PeopleList.FetchPeople.Request)
}

protocol PeopleListDataStore
{
    //var name: String { get set }
}

class PeopleListInteractor: PeopleListBusinessLogic, PeopleListDataStore
{
    var presenter: PeopleListPresentationLogic?
    var worker: PeopleListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func fethcPeople(request: PeopleList.FetchPeople.Request)
    {
        worker = PeopleListWorker()
        let people = worker?.fetchPeople() ?? []
        
        let response = PeopleList.FetchPeople.Response(people: people)
        presenter?.presentPeople(response: response)
    }
}
